stripe.secret.key=sk_test_51T3IGfCIZ8Yq1yzfQqe1It1oiqJkexKygC9tTJN5mh3Bt2784py7Aw8kqLbH0KrJZAfyVKlObqaz29Brf8UFzNoW00ifYDNXt7
stripe.currency=eur
brevo.api.key=
brevo.sender.email=
brevo.sender.name=Bledna

