stripe.secret.key=sk_test_51T3IGfCIZ8Yq1yzfQqe1It1oiqJkexKygC9tTJN5mh3Bt2784py7Aw8kqLbH0KrJZAfyVKlObqaz29Brf8UFzNoW00ifYDNXt7
stripe.currency=eur
brevo.api.key=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
brevo.sender.email=mariemabbes098@gmail.com
brevo.sender.name=Bledna

